// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqI5juIUtjHT3GcVfDIvanNQUFS5S5Jo',
    appId: '1:574274568290:web:3f90f1caa04dacbd42d13b',
    messagingSenderId: '574274568290',
    projectId: 'cj-project-da850',
    authDomain: 'cj-project-da850.firebaseapp.com',
    databaseURL: 'https://cj-project-da850-default-rtdb.firebaseio.com',
    storageBucket: 'cj-project-da850.appspot.com',
    measurementId: 'G-WCDJM6KSMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmfNp_858FF5GmmMhHFsY50SW5v6v_4Uk',
    appId: '1:574274568290:android:72a7faa9ddef54d842d13b',
    messagingSenderId: '574274568290',
    projectId: 'cj-project-da850',
    databaseURL: 'https://cj-project-da850-default-rtdb.firebaseio.com',
    storageBucket: 'cj-project-da850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAsorDbQzE4q5GqEWSgycOT3-KAuVhqAY',
    appId: '1:574274568290:ios:235ab3653eda3c6342d13b',
    messagingSenderId: '574274568290',
    projectId: 'cj-project-da850',
    databaseURL: 'https://cj-project-da850-default-rtdb.firebaseio.com',
    storageBucket: 'cj-project-da850.appspot.com',
    iosBundleId: 'com.example.cjWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAsorDbQzE4q5GqEWSgycOT3-KAuVhqAY',
    appId: '1:574274568290:ios:235ab3653eda3c6342d13b',
    messagingSenderId: '574274568290',
    projectId: 'cj-project-da850',
    databaseURL: 'https://cj-project-da850-default-rtdb.firebaseio.com',
    storageBucket: 'cj-project-da850.appspot.com',
    iosBundleId: 'com.example.cjWebapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcqI5juIUtjHT3GcVfDIvanNQUFS5S5Jo',
    appId: '1:574274568290:web:338df3b4e116943342d13b',
    messagingSenderId: '574274568290',
    projectId: 'cj-project-da850',
    authDomain: 'cj-project-da850.firebaseapp.com',
    databaseURL: 'https://cj-project-da850-default-rtdb.firebaseio.com',
    storageBucket: 'cj-project-da850.appspot.com',
    measurementId: 'G-B8F5SBQ9MJ',
  );
}
